openapi: 3.0.0
info:
  title: Blog api
  version: 1.0.0
servers:
  - url: http://localhost/
    description: Local server

paths:
  /api/v1/health-check:
    $ref: "./Controllers/health-check.yaml"
  /api/v1/user/generate-token:
    $ref: "./Controllers/User/Documentation/generate-token.yaml"
